---
# tasks file for code_gov_update
- name: Create the /var/cyhy/client-cert-update directory
  ansible.builtin.file:
    path: /var/cyhy/client-cert-update
    state: directory
    mode: 0755

- name: Install the Docker Compose configuration
  ansible.builtin.copy:
    dest: /var/cyhy/client-cert-update
    mode: 0644
    src: docker-compose.yml
