---
version: "3.2"

secrets:
  aws_config:
    file: secrets/aws_config
  scan_read_creds:
    file: secrets/scan_read_creds.yml

services:
  update:
    command:
      - "--db-creds-file=/run/secrets/scan_read_creds.yml"
      - "--from=reports@cyber.dhs.gov"
      - "--to=fnr.bod@hq.dhs.gov"
      - "--cc=ncats-dev@beta.dhs.gov,ncats@hq.dhs.gov"
      - "--reply=ncats-dev@beta.dhs.gov"
      - >-
        --subject="Latest list of web hosts that require authentication
        via client certificates"
      - "--text=body.txt"
      - "--html=body.html"
      - "--log-level=info"
    environment:
      - AWS_CONFIG_FILE=/run/secrets/aws_config
      - AWS_PROFILE=default
    image: dhsncats/client-cert-update:0.0.2
    secrets:
      - source: aws_config
        target: aws_config
      - source: scan_read_creds
        target: scan_read_creds.yml
